name: clone my stars
on:
  workflow_dispatch:
  schedule:
  - cron: 37 0 * * *

env:
  # Hexo 编译后使用此 git 用户部署到 github 仓库
  GIT_USER: valetzx
  # Hexo 编译后使用此 git 邮箱部署到 github 仓库
  GIT_EMAIL: 550029691@qq.com
  # Hexo 编译后要部署的 github 仓库
  GIT_DEPLOY_REPO: valetzx/stars
  # Hexo 编译后要部署到的分支
  GIT_DEPLOY_BRANCH: main
  # 注意替换为你的 GitHub 源仓库地址
  GIT_SOURCE_REPO: git@github.com:valetzx/stars.git

jobs:
  awesome-stars:
    name: update stars
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: add time #添加时间，防止无内容可commit
      run: | 
        sudo timedatectl set-timezone "Asia/Shanghai"
        echo `date +"%Y-%m-%d %H:%M:%S"` begin > checktime.log

    - name: update repo
      env:
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      run: |
        git submodule update --init

    - name: Push clone
    # 将写入的文件推送到仓库
      run: |
        ls -a
        git init && git add .
        git config user.name "valetzx"
        git config user.email "550029691@qq.com"
        git add .
        git commit -m "GitHub Actions Clone at $(date +'%Y-%m-%d %H:%M:%S')"
        git push --quiet "https://${{ secrets.MY_TOKEN }}@github.com/valetzx/stars" HEAD:main