name: update awesome-stars
on:
  workflow_dispatch:
  schedule:
  - cron: 27 0 * * *
jobs:
  awesome-stars:
    name: update stars
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install starred
    - name: update repo
      env:
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      run: |
        starred --username valetzx --sort > README.md
        
    - name: Push README.md
    # 将写入的文件推送到仓库
      run: |
        ls -a
        git init && git add README.md
        git config user.name "valetzx"
        git config user.email "550029691@qq.com"
        git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
        git push --quiet "https://${{ secrets.MY_TOKEN }}@github.com/valetzx/stars" main:main