name: update my stars
on: 
  push:
    branches: 
      - master
  schedule:
    - cron: '27 0 * * *'
  watch:
    types: [started]

env:
  GIT_USER: valetzx
  GIT_EMAIL: 550029691@qq.com
  GIT_DEPLOY_REPO: valetzx/stars
  GIT_DEPLOY_BRANCH: main
  # 注意替换为你的 GitHub 源仓库地址 这里整个env似乎没啥作用
  GIT_SOURCE_REPO: git@github.com:valetzx/stars.git

jobs:
  awesome-stars:
    name: update stars
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install starred

    - name: add time #添加时间，防止无内容可commit
      run: | 
        sudo timedatectl set-timezone "Asia/Shanghai"
        echo `date +"%Y-%m-%d %H:%M:%S"` begin > checktime.log
        
    - name: update repo
      env:
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      run: |
        starred --username valetzx --sort > README.md
        sed -i '1 d' README.md
        sed -i '2 d' README.md
        sed -i '3 d' README.md
        sed -i '4 d' README.md
        sed -i '/License/{n;d}' README.md  
        sed -i '/License/{n;d}' README.md  
        sed -i '/License/{n;d}' README.md  
        sed -i '/License/{n;d}' README.md
        find . -name README.md|xargs sed -i '/Contents/i ### 本仓库意备份Replit白嫖收藏，可以在 https://github.com/stars/valetzx/lists/replit 获取一键部署的仓库，记得Star！如果您有合适的仓库也可以发送issue或PR新文件夹 '
        find . -name README.md|xargs sed -i '/License/a ### 本README使用 https://github.com/maguowei/starred 项目生成 '
        find . -name README.md|xargs sed -i '/Contents/i\ '
        find . -name README.md|xargs sed -i '/License/a\ '
        sed -i '1 d' README.md

    - name: Push README.md
    # 将写入的文件推送到仓库
      run: |
        git init && git add README.md
        git config user.name "valetzx"
        git config user.email "550029691@qq.com"
        git add README.md
        git add checktime.log
        git commit -m "GitHub Actions Make Star at $(date +'%Y-%m-%d %H:%M:%S')"
        git push --quiet "https://${{ secrets.MY_TOKEN }}@github.com/valetzx/stars" HEAD:main
