name: update my stars
on:
  workflow_dispatch:
  schedule:
  - cron: 27 0 * * *

env:
  # Hexo 编译后使用此 git 用户部署到 github 仓库
  GIT_USER: valetzx
  # Hexo 编译后使用此 git 邮箱部署到 github 仓库
  GIT_EMAIL: 550029691@qq.com
  # Hexo 编译后要部署的 github 仓库
  GIT_DEPLOY_REPO: valetzx/stars
  # Hexo 编译后要部署到的分支
  GIT_DEPLOY_BRANCH: main
  # 注意替换为你的 GitHub 源仓库地址
  GIT_SOURCE_REPO: git@github.com:valetzx/stars.git

jobs:
  awesome-stars:
    name: update stars
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install starred
    - name: update repo
      env:
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      run: |
        starred --username valetzx --sort > README.md
        sed -i '1 d' README.md
        sed -i '2 d' README.md
        sed -i '3 d' README.md
        sed -i '4 d' README.md
        sed -i '/License/{n;d}' README.md  
        sed -i '/License/{n;d}' README.md  
        sed -i '/License/{n;d}' README.md  
        sed -i '/License/{n;d}' README.md
        find . -name README.md|xargs sed -i '/Contents/i ### 本仓库意备份Replit白嫖仓库，可以在 https://github.com/stars/valetzx/lists/replit 获取一键部署的仓库，记得Star！ '
        find . -name README.md|xargs sed -i '/License/a ### 本README使用 https://github.com/maguowei/starred 项目生成 '
        find . -name README.md|xargs sed -i '/Contents/i {n;d}'
        find . -name README.md|xargs sed -i '/License/a {n;d}'

    - name: Push README.md
    # 将写入的文件推送到仓库
      run: |
        ls -a
        git init && git add README.md
        git config user.name "valetzx"
        git config user.email "550029691@qq.com"
        git add README.md
        git commit -m "GitHub Actions Make Star at $(date +'%Y-%m-%d %H:%M:%S')"
        git push --quiet "https://${{ secrets.MY_TOKEN }}@github.com/valetzx/stars" HEAD:main